### ISSUE TITLE
congratulations on the project

### ISSUE THREAD

**Issue by NrSheik** [daniellwdb/rok-title-keeper#16]
congrats on the project, I had a little trouble installing it but I managed it, an interesting idea would be negative titles, I'm one of the kings of my kingdom and talking we saw that it seems to be an interesting function.

**Comment by daniellwdb** [comment]
Hi, I don't play the game so I am not sure what that means. You can contact me on Discord: daniellwdb

**Comment by Usamarajputrok** [comment]
@NrSheik hi sir can you help me to setup bot
