### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by inhwa-son** [daniellwdb/rok-title-keeper#27]
First of all, thank you for making such a great program

1. Open Rok Command Error 
```
Command failed: C:\rok-title-keeper\platform-tools\adb.exe -s emulator-5554 shell monkey -p com.lilithgame.roc.gp 1
```
add-title.ts  69Line ```await rebootRoK(device);``` If you remove this Line, you can start

2. Title GUI Error
When title, clicking on the wrong Position and unable to process your title request.
There were many cases where requests could not be processed.

Thank you.

**Comment by daniellwdb** [comment]
Hi, make sure you install platform-tools from the link provided in the README as that version supports the `monkey` command. Also carefully go through step 4 in "Getting started" to fix the second issue

**Comment by daniellwdb** [comment]
For 1 it could also be that you installed a different version of Rise of Kingdoms so the bundle id does not match. Could you tell me what version you installed?

**Comment by inhwa-son** [comment]
The installed version is not a global version, Bundle id was different, I corrected this part and everything was solved Thank you.
Do you have any additional plans to support Pass verification?

**Comment by Usamarajputrok** [comment]
@inhwa-son hi sir i need your help to setup bot
