### ISSUE TITLE
I try to open bot but I failed 

### ISSUE THREAD

**Issue by Usamarajputrok** [daniellwdb/rok-title-keeper#29]
Sir i need your help to run bot please guide me and give your discord 🙏
@daniellwdb 
My discord is boss2991
![Screenshot (176)](https://github.com/daniellwdb/rok-title-keeper/assets/130558028/8bd5756a-2cf3-44f9-b668-985663a796c9)

**Comment by daniellwdb** [comment]
Carefully go through the README. In Getting started > 2, you see:
> Set the OPENCV4NODEJS_DISABLE_AUTOBUILD=1 environment variable and run npx build-opencv --version 4.6.0 rebuild.
