### ISSUE TITLE
Hi sir i am facing this issue 

### ISSUE THREAD

**Issue by Usamarajputrok** [daniellwdb/rok-title-keeper#30]
@daniellwdb 

![Screenshot_9](https://github.com/daniellwdb/rok-title-keeper/assets/130558028/faca3fcd-51cd-4e7f-84e2-05edbfdd3ff1)

**Comment by daniellwdb** [comment]
You need to set the environment variable to where you installed the opencv software. You can find alternative ways of installing it [here](https://www.npmjs.com/package/@u4/opencv4nodejs)
